### ISSUE TITLE
Got connect failed: ENETUNREACH (Network is unreachable) when setting UseSystemSending=FALSE

### ISSUE THREAD

**Issue by t53864** [klinker41/android-smsmms#107]
Hi,
Thanks for the project. I am using this on a S6 running v5.1.1 with DATA on and Wifi off.

I am able to send MMS successfully when UseSystemSending is set to TRUE. 

But, when changing it to FALSE, I got HTTP error:

09-19 14:15:17.263 E/MmsHttpClient(11640): HTTP: IO failure
09-19 14:15:17.263 E/MmsHttpClient(11640): java.net.ConnectException: failed to connect to proxy.xxx/nnn.nnn.nnn.nnn (port 80) after 60000ms: connect failed: ENETUNREACH (Network is unreachable)
09-19 14:15:17.263 E/MmsHttpClient(11640): 	at libcore.io.IoBridge.connect(IoBridge.java:124)
09-19 14:15:17.263 E/MmsHttpClient(11640): 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
09-19 14:15:17.263 E/MmsHttpClient(11640): 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)

Anyone has experienced this error?
Any help is appreciated.

Thanks,
Terry

**Comment by t53864** [comment]
**Follow up:**
- since I am using a US sim in Canada, it is doing Roaming. And I forgot to turn on 'International Roaming'. That's why it is not connecting.
- However, it is strange that when doing 'UseSystemSending', it will turn ON the international roaming automatically before sending MMS and turning it OFF after; as I see the "4G/LTE" icon shown up in the status bar for a second when the MMS is being sent.
