### ISSUE TITLE
Not supported in target SDK version 23. could you help? 

### ISSUE THREAD

**Issue by jstevenkim** [klinker41/android-smsmms#108]
ava.lang.UnsupportedOperationException: This method is not supported in target SDK version 23 and above
09-28 12:43:42.116 14859-16427/com.mms.remote.y001 W/System.err:     at android.net.ConnectivityManager.unsupportedStartingFrom(ConnectivityManager.java:3745)
09-28 12:43:42.116 14859-16427/com.mms.remote.y001 W/System.err:     at android.net.ConnectivityManager.checkLegacyRoutingApiAccess(ConnectivityManager.java:3762)
09-28 12:43:42.116 14859-16427/com.mms.remote.y001 W/System.err:     at android.net.ConnectivityManager.startUsingNetworkFeature(ConnectivityManager.java:1285)

**Comment by LoungeKatt** [comment]
See https://github.com/klinker41/android-smsmms/issues/115
