### ISSUE TITLE
Sending MMS not working on HTC on Sprint

### ISSUE THREAD

**Issue by kking937** [klinker41/android-smsmms#120]
I have the sample app running, but I am getting an error when I try to send the picture.  Is is all of the output.

02-10 10:46:28.774 30270-30270/? I/art: Late-enabling -Xcheck:jni
02-10 10:46:28.774 30270-30270/? I/art: VMHOOK: rlim_cur : 0 pid:30270
02-10 10:46:28.792 30270-30277/? I/art: Debugger is no longer active
02-10 10:46:28.792 30270-30277/? I/art: Starting a blocking GC Instrumentation
02-10 10:46:28.808 30270-30270/? W/ActivityThread: Application com.klinker.android.send_message.sample is waiting for the debugger on port 8100...
02-10 10:46:28.810 30270-30270/? I/System.out: Sending WAIT chunk
02-10 10:46:30.849 30270-30277/com.klinker.android.send_message.sample I/art: Debugger is active
02-10 10:46:31.012 30270-30270/com.klinker.android.send_message.sample I/System.out: Debugger has connected
02-10 10:46:31.012 30270-30270/com.klinker.android.send_message.sample I/System.out: waiting for debugger to settle...
02-10 10:46:31.213 30270-30270/com.klinker.android.send_message.sample I/System.out: waiting for debugger to settle...
02-10 10:46:31.413 30270-30270/com.klinker.android.send_message.sample I/System.out: waiting for debugger to settle...
02-10 10:46:31.617 30270-30270/com.klinker.android.send_message.sample I/System.out: waiting for debugger to settle...
02-10 10:46:31.817 30270-30270/com.klinker.android.send_message.sample I/System.out: waiting for debugger to settle...
02-10 10:46:32.018 30270-30270/com.klinker.android.send_message.sample I/System.out: waiting for debugger to settle...
02-10 10:46:32.218 30270-30270/com.klinker.android.send_message.sample I/System.out: waiting for debugger to settle...
02-10 10:46:32.419 30270-30270/com.klinker.android.send_message.sample I/System.out: debugger has settled (1495)
02-10 10:46:32.588 30270-30270/com.klinker.android.send_message.sample W/System: ClassLoader referenced unknown path: /data/app/com.klinker.android.send_message.sample-1/lib/arm64
02-10 10:46:32.610 30270-30270/com.klinker.android.send_message.sample I/InstantRun: starting instant run server: is main process
02-10 10:46:32.915 30270-30270/com.klinker.android.send_message.sample W/SystemReader: Cannot find supportVzwLine1NumberRule, use default value instead
02-10 10:46:32.924 30270-30270/com.klinker.android.send_message.sample W/SystemReader: Cannot find supportVzwLine1NumberRule, use default value instead
02-10 10:46:33.090 30270-30326/com.klinker.android.send_message.sample I/Adreno: QUALCOMM build                   : b6da14b, I47548ba842
                                                                                 Build Date                       : 12/07/16
                                                                                 OpenGL ES Shader Compiler Version: XE031.09.00.03
                                                                                 Local Branch                     : 
                                                                                 Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.BR.1.3.6_RB1.07.00.00.255.023
                                                                                 Remote Branch                    : NONE
                                                                                 Reconstruct Branch               : NOTHING
02-10 10:46:33.450 30270-30275/com.klinker.android.send_message.sample I/art: Do partial code cache collection, code=23KB, data=27KB
02-10 10:46:33.451 30270-30275/com.klinker.android.send_message.sample I/art: After code cache collection, code=22KB, data=27KB
02-10 10:46:33.451 30270-30275/com.klinker.android.send_message.sample I/art: Increasing code cache capacity to 128KB
02-10 10:46:44.564 30270-30270/com.klinker.android.send_message.sample V/ApnUtils: tag: bool value: enabledMMS - true
02-10 10:46:44.591 30270-30270/com.klinker.android.send_message.sample V/ApnUtils: tag: int value: maxMessageSize - 1048576
02-10 10:46:44.600 30270-30270/com.klinker.android.send_message.sample V/ApnUtils: tag: int value: maxImageHeight - 1944
02-10 10:46:44.610 30270-30270/com.klinker.android.send_message.sample V/ApnUtils: tag: int value: maxImageWidth - 2592
02-10 10:46:44.619 30270-30270/com.klinker.android.send_message.sample V/ApnUtils: tag: int value: recipientLimit - 40
02-10 10:46:44.628 30270-30270/com.klinker.android.send_message.sample V/ApnUtils: tag: bool value: enableMultipartSMS - true
02-10 10:46:44.638 30270-30270/com.klinker.android.send_message.sample V/ApnUtils: tag: int value: smsToMmsTextThreshold - 6
02-10 10:46:44.647 30270-30270/com.klinker.android.send_message.sample V/ApnUtils: tag: bool value: enableSlideDuration - false
02-10 10:46:44.656 30270-30270/com.klinker.android.send_message.sample V/ApnUtils: tag: int value: maxMessageTextSize - -1
02-10 10:46:44.663 30270-30270/com.klinker.android.send_message.sample V/ApnUtils: tag: int value: maxSubjectLength - 80
02-10 10:46:44.671 30270-30270/com.klinker.android.send_message.sample V/ApnUtils: tag: string value: emailGatewayNumber - 6245
02-10 10:46:44.680 30270-30270/com.klinker.android.send_message.sample V/ApnUtils: tag: bool value: enableMMSReadReports - false
02-10 10:46:44.689 30270-30270/com.klinker.android.send_message.sample V/ApnUtils: tag: bool value: enableSMSDeliveryReports - false
02-10 10:46:44.698 30270-30270/com.klinker.android.send_message.sample V/ApnUtils: tag: bool value: enableMMSDeliveryReports - false
02-10 10:46:44.707 30270-30270/com.klinker.android.send_message.sample V/ApnUtils: tag: string value: httpParams - X-MDN: ##LINE1##|Proxy-Authorization: Basic ##NAI##
02-10 10:46:44.715 30270-30270/com.klinker.android.send_message.sample V/ApnUtils: tag: string value: naiSuffix - :pcs
02-10 10:46:44.723 30270-30270/com.klinker.android.send_message.sample V/ApnUtils: tag: bool value: supportMmsContentDisposition - false
02-10 10:46:44.732 30270-30270/com.klinker.android.send_message.sample D/MessageAccCustomizeFlag: sense_version=8.0
02-10 10:46:44.736 30270-30270/com.klinker.android.send_message.sample D/TelephonyManager:  getMmsUserAgent > 2PQ93 SPRINT
02-10 10:46:44.736 30270-30270/com.klinker.android.send_message.sample D/MessageAccCustomizeFlag: sense_version=8.0
02-10 10:46:44.737 30270-30275/com.klinker.android.send_message.sample I/art: Do partial code cache collection, code=51KB, data=55KB
02-10 10:46:44.737 30270-30275/com.klinker.android.send_message.sample I/art: After code cache collection, code=51KB, data=55KB
02-10 10:46:44.737 30270-30275/com.klinker.android.send_message.sample I/art: Increasing code cache capacity to 256KB
02-10 10:46:44.738 30270-30270/com.klinker.android.send_message.sample D/TelephonyManager: getMmsUAProfUrl: http://device.sprintpcs.com/HTC/2PQ93-SPRINT/2186512.rdf
02-10 10:46:44.748 30270-30270/com.klinker.android.send_message.sample V/ApnUtils: mcc: 310 mnc: 120
02-10 10:46:46.870 30270-30270/com.klinker.android.send_message.sample V/ApnUtils: MMSC: http://mms.sprintpcs.com, MMS Proxy: 68.28.31.7, MMS Port: 80
02-10 10:46:46.883 30270-30270/com.klinker.android.send_message.sample I/Choreographer: Skipped 139 frames!  The application may be doing too much work on its main thread.
02-10 10:46:51.947 30270-30582/com.klinker.android.send_message.sample V/Transaction: using lollipop method for sending sms
02-10 10:46:51.957 30270-30582/com.klinker.android.send_message.sample V/Transaction: using system method for sending
02-10 10:46:51.985 30270-30582/com.klinker.android.send_message.sample W/SystemReader: Cannot find supportVzwLine1NumberRule, use default value instead
02-10 10:46:52.147 30270-30582/com.klinker.android.send_message.sample E/Transaction: error using system sending method
                                                                                      com.google.android.mms.MmsException: unable to update content://mms/1518284812129/part/0
                                                                                          at com.google.android.mms.pdu_alt.PduPersister.persistData(PduPersister.java:838)
                                                                                          at com.google.android.mms.pdu_alt.PduPersister.persistPart(PduPersister.java:761)
                                                                                          at com.google.android.mms.pdu_alt.PduPersister.persist(PduPersister.java:1438)
                                                                                          at com.klinker.android.send_message.Transaction.sendMmsThroughSystem(Transaction.java:619)
                                                                                          at com.klinker.android.send_message.Transaction.sendMmsMessage(Transaction.java:469)
                                                                                          at com.klinker.android.send_message.Transaction.sendNewMessage(Transaction.java:136)
                                                                                          at com.klinker.android.messaging_sample.MainActivity$7.run(MainActivity.java:200)
                                                                                          at java.lang.Thread.run(Thread.java:761)

**Comment by kking937** [comment]
But what if I don't want it set as the default app?

**Comment by klinker41** [comment]
Then you can't send MMS.
