### ISSUE TITLE
Receive MMS crashing the app

### ISSUE THREAD

**Issue by markandroid2999** [klinker41/android-smsmms#123]
I have the following class for receiving MMS

```
public class MmsReceiver extends MmsReceivedReceiver {
    private Long conversationId = null;

    @Override
    public void onMessageReceived(Uri messageUri) {

    }
}
```

The overridden onMessageReceived method is empty, but when I send my phone an MMS I get a fatal exception

```
FATAL EXCEPTION: main
                                                                Process: com.rev.future, PID: 15942
                                                                java.lang.RuntimeException: Unable to start receiver com.rev.future.MmsReceiver: java.lang.NullPointerException: println needs a message
                                                                    at android.app.ActivityThread.handleReceiver(ActivityThread.java:3039)
                                                                    at android.app.ActivityThread.-wrap18(ActivityThread.java)
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1557)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:154)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
                                                                 Caused by: java.lang.NullPointerException: println needs a message
                                                                    at android.util.Log.println_native_inner(Native Method)
                                                                    at android.util.Log.println_native(Log.java:294)
                                                                    at android.util.Log.v(Log.java:306)
                                                                    at com.klinker.android.send_message.MmsReceivedReceiver.onReceive(MmsReceivedReceiver.java:87)
                                                                    at android.app.ActivityThread.handleReceiver(ActivityThread.java:3032)
                                                                    at android.app.ActivityThread.-wrap18(ActivityThread.java) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1557) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                    at android.os.Looper.loop(Looper.java:154) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:6123) 
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757) 
```

Below is my manifest file

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.rev.future">

    <uses-permission android:name="android.permission.SEND_SMS" />
    <uses-permission android:name="android.permission.READ_SMS" />
    <uses-permission android:name="android.permission.WRITE_SMS" />
    <uses-permission android:name="android.permission.RECEIVE_SMS" />
    <uses-permission android:name="android.permission.RECEIVE_MMS" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-permission android:name="android.provider.Telephony.SMS_RECEIVED" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
    <uses-permission android:name="android.permission.CHANGE_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_SETTINGS" />

    <application
        android:allowBackup="true"
        android:debuggable="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme"
        tools:ignore="HardcodedDebugMode">
        <activity android:name=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

        <!-- BroadcastReceiver that listens for incoming SMS messages -->
        <receiver
            android:name=".SmsReceiver"
            android:permission="android.permission.BROADCAST_SMS">
            <intent-filter>
                <action android:name="android.provider.Telephony.SMS_DELIVER" />
            </intent-filter>
        </receiver>

        <!-- BroadcastReceiver that listens for incoming MMS messages -->
        <receiver
            android:name=".MmsReceiver"
            android:permission="android.permission.BROADCAST_WAP_PUSH">
            <intent-filter>
                <action android:name="android.provider.Telephony.WAP_PUSH_DELIVER" />

                <data android:mimeType="application/vnd.wap.mms-message" />
            </intent-filter>
        </receiver>

        <!-- Activity that allows the user to send new SMS/MMS messages -->
        <activity android:name=".ComposeSmsActivity">
            <intent-filter>
                <action android:name="android.intent.action.SEND" />
                <action android:name="android.intent.action.SENDTO" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data android:scheme="sms" />
                <data android:scheme="smsto" />
                <data android:scheme="mms" />
                <data android:scheme="mmsto" />
            </intent-filter>
        </activity>

        <!-- Service that delivers messages from the phone "quick response" -->
        <service
            android:name=".HeadlessSmsSendService"
            android:exported="true"
            android:permission="android.permission.SEND_RESPOND_VIA_MESSAGE">
            <intent-filter>
                <action android:name="android.intent.action.RESPOND_VIA_MESSAGE" />

                <category android:name="android.intent.category.DEFAULT" />

                <data android:scheme="sms" />
                <data android:scheme="smsto" />
                <data android:scheme="mms" />
                <data android:scheme="mmsto" />
            </intent-filter>
        </service>
        <activity android:name=".PermissionActivity" />

        <service android:name=".MyFirebaseInstanceIDService">
            <intent-filter>
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
            </intent-filter>
        </service>
        <service
            android:name=".MyFirebaseMessagingService">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT"/>
            </intent-filter>
        </service>

    </application>

</manifest>
```

Have I found a bug or something I am doing wrong?

**Comment by markandroid2999** [comment]
I did more research on this. This is where exception happens. This is inside the MmsReceivedReceiver class. I do see the "MMS has finished downloading, persisting it to the database" printed in the logs then followed by the exception. I suppose  intent.getStringExtra("file_path"); is returning null.


        Log.v("MmsReceivedReceiver", "MMS has finished downloading, persisting it to the database");
        String path = intent.getStringExtra("file_path");
        Log.v("MmsReceivedReceiver", path);           <-- This is the line causing the exeption

**Comment by markandroid2999** [comment]
I downloaded and ran the sample application which has the following

```
public class MmsReceiver extends PushReceiver {

}
```
It causes no crash I get the following logs

```
03-13 19:02:57.031 18675-18675/com.klinker.android.send_message.sample V/Mms: android.provider.Telephony.WAP_PUSH_DELIVER application/vnd.wap.mms-message
03-13 19:02:57.039 18675-18675/com.klinker.android.send_message.sample V/Mms: Received PUSH Intent: Intent { act=android.provider.Telephony.WAP_PUSH_DELIVER typ=application/vnd.wap.mms-message flg=0x18000010 cmp=com.klinker.android.send_message.sample/com.klinker.android.messaging_sample.MmsReceiver (has extras) }
03-13 19:02:57.048 18675-18675/com.klinker.android.send_message.sample V/MmsConfig: tag: int value: maxMessageSize - 1048576
03-13 19:02:57.052 18675-18675/com.klinker.android.send_message.sample V/MmsConfig: tag: int value: maxImageHeight - 1944
03-13 19:02:57.055 18675-18675/com.klinker.android.send_message.sample V/MmsConfig: tag: int value: maxImageWidth - 2592
03-13 19:02:57.059 18675-18675/com.klinker.android.send_message.sample V/MmsConfig: tag: int value: recipientLimit - 10
03-13 19:02:57.062 18675-18675/com.klinker.android.send_message.sample E/MmsConfig: MmsConfig.loadMmsSettings mms_config.xml missing uaProfUrl setting
03-13 19:02:57.070 18675-18675/com.klinker.android.send_message.sample V/mms_receiver: com.klinker.android.send_message.sample received and aborted
03-13 19:02:57.070 18675-18794/com.klinker.android.send_message.sample V/Mms: receiving a new mms message
03-13 19:02:57.219 18675-18794/com.klinker.android.send_message.sample V/Mms: receiving on a lollipop+ device
03-13 19:02:57.243 18675-18794/com.klinker.android.send_message.sample V/DownloadManager: receiving with system method
03-13 19:02:57.279 18675-18794/com.klinker.android.send_message.sample V/Mms: PUSH Intent processed.
```
But if I change extends PushReceiver to extends MmsReceivedReceiver then the same exception happens.

**Comment by klinker41** [comment]
I don't think you're importing the right receivers in your manifest. There should be 3 according to the sample:

```xml
<receiver
    android:name=".MmsReceiver"
    android:permission="android.permission.BROADCAST_WAP_PUSH">
    <intent-filter>
        <action android:name="android.provider.Telephony.WAP_PUSH_DELIVER" />
        <data android:mimeType="application/vnd.wap.mms-message" />
    </intent-filter>
</receiver>

<receiver
    android:name="com.klinker.android.send_message.MmsSentReceiver"
    android:taskAffinity="com.klinker.android.messaging.MMS_SENT"/>

<receiver
    android:name="com.klinker.android.send_message.MmsReceivedReceiver"
    android:taskAffinity="com.klinker.android.messaging.MMS_RECEIVED"/>
```

MmsMessageReceiver doesn't do the same thing as PushReceiver by the looks of things, so you need both and you're trying to combine them into 1, which means the correct extras aren't available.

**Comment by markandroid2999** [comment]
In the sample there is MmsReceiver that extends PushReceiver. Do I make another class that extends MmsReceivedReceiver?
