### ISSUE TITLE
HTTP: 302 MmsHttpException while sending MMS to emulator

### ISSUE THREAD

**Issue by georgi8706** [klinker41/android-smsmms#124]
Hi everyone,
I managed to send an MMS to real device successfully, but when I try to send it from the emulator to the same emulator it throws exception HTTP 302 (HTTP Status-Code 302: Temporary Redirect). I am struggling this problem for quite long time so I really don't have more ideas of fixing the problem :(. "To" number is just a simple number like "1" and "From" number is my emulator number "15555215554". This is the log:

Time	Device Name	Type	PID	Tag	Message
03-21 00:35:23.728	23_xhdpi_4.7	Error	2834	MmsService	com.android.mms.service.exception.MmsHttpException: Found
	at com.android.mms.service.MmsHttpClient.execute(MmsHttpClient.java:179)
	at com.android.mms.service.SendRequest.doHttp(SendRequest.java:73)
	at com.android.mms.service.MmsRequest.execute(MmsRequest.java:171)
	at com.android.mms.service.MmsService$2.run(MmsService.java:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
 Removing from current network NetworkAgentInfo [MOBILE (LTE) - 100], leaving 3 requests.
03-21 00:35:23.728	23_xhdpi_4.7	Debug	2834	MmsService	[SendRequest@979c09d] MmsNetworkManager: release, count=0
03-21 00:35:23.728	23_xhdpi_4.7	Debug	2834	MmsService	[SendRequest@979c09d] HTTP: 302 Found
03-21 00:35:23.324	23_xhdpi_4.7	Info	2834	MmsService	[SendRequest@979c09d] HTTP: User-Agent=GoldfishNexus
03-21 00:35:23.324	23_xhdpi_4.7	Info	2834	MmsService	[SendRequest@979c09d] HTTP: UaProfUrl=http://gsm.lge.com/html/gsm/Nexus5-M3.xml
03-21 00:35:23.324	23_xhdpi_4.7	Debug	2834	MmsService	[SendRequest@979c09d] HTTP: POST http://mms.msg.eng.t-mobile.com[42], PDU size=158
03-21 00:35:23.324	23_xhdpi_4.7	Info	2834	MmsService	[SendRequest@979c09d] Using APN [ mmsc=http://mms.msg.eng.t-mobile.com/mms/wapenc name=T-Mobile US apn=epc.tmobile.com bearer_bitmask=0 protocol=IP roaming_protocol=IP authtype=-1 server=* user=none password=none]
03-21 00:35:23.322	23_xhdpi_4.7	Info	2834	MmsService	NetworkCallbackListener.onAvailable: network=100
03-21 00:35:23.322	23_xhdpi_4.7	Info	2834	MmsService	[SendRequest@979c09d] Loading APN using name epc.tmobile.com
03-21 00:35:23.322	23_xhdpi_4.7	Debug	2834	MmsService	[SendRequest@979c09d] APN name is epc.tmobile.com
03-21 00:35:23.318	23_xhdpi_4.7	Debug	2834	MmsService	[SendRequest@979c09d] MmsNetworkManager: start new network request

**Comment by georgi8706** [comment]
I have some progress. My MMSC (Settings->Wireless&Network->Cellular Network Settings->Access Point) was not secured (only http). I manually edited to httpS and now the MMS is sent. But I don't understand how the default Android messaging app manages to redirect successfully... I want to be able to send the MMS no matter if it is http or https..
