### ISSUE TITLE
no such column: creator Exception

### ISSUE THREAD

**Issue by pacoblack** [klinker41/android-smsmms#151]
2019-02-27 14:56:41.915 1860-16609/? E/SQLiteLog: (1) no such column: creator
2019-02-27 14:56:41.923 1860-16609/? E/SqliteWrapper: Catch a SQLiteException when update: 
    android.database.sqlite.SQLiteException: no such column: creator (code 1): , while compiling: UPDATE pdu SET creator=?,seen=?,advanced_seen=?,sub_id=?,read=?,resp_st=?,date=?,m_id=?,sync_state=? WHERE (deleted=0) AND (_id=154)
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
        at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
        at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1577)
        at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1525)
        at com.android.providers.telephony.MmsProvider.update(MmsProvider.java:1339)
        at android.content.ContentProvider$Transport.update(ContentProvider.java:356)
        at android.content.ContentResolver.update(ContentResolver.java:1425)
        at com.google.android.mms.util.SqliteWrapper.update(SqliteWrapper.java:91)
        at com.android.mms.service.SendRequest.persistIfRequired(SendRequest.java:218)
        at com.android.mms.service.MmsRequest.processResult(MmsRequest.java:214)
        at com.android.mms.service.MmsRequest.execute(MmsRequest.java:202)
        at com.android.mms.service.MmsService$2.run(MmsService.java:414)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:760)

**Comment by pacoblack** [comment]
now i can't receive a delivery report
