### ISSUE TITLE
Unable to start receiver com.example.mms_test.MmsReceiver: java.lang.NullPointerException: println needs a message

### ISSUE THREAD

**Issue by tesselode** [klinker41/android-smsmms#181]
I created a blank Android app to test this library. In it, I have a very simple `MmsReceiver` class:

```java
public class MmsReceiver extends MmsReceivedReceiver {
    @Override
    public void onMessageReceived(Context context, Uri uri) {
        System.out.println("MMS received:");
    }

    @Override
    public void onError(Context context, String s) {
        System.out.println("Error receiving MMS:");
    }
}
```

It's set up as a receiver in the manifest:
```xml
<receiver android:name=".MmsReceiver"
    android:permission="android.permission.BROADCAST_WAP_PUSH">
    <intent-filter>
        <action android:name="android.provider.Telephony.WAP_PUSH_DELIVER" />
        <data android:mimeType="application/vnd.wap.mms-message" />
    </intent-filter>
</receiver>
```

When I send an image to my phone via TextNow, I get the following output in the console:
```
V/MmsReceivedReceiver: MMS has finished downloading, persisting it to the database
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.mms_test, PID: 7836
    java.lang.RuntimeException: Unable to start receiver com.example.mms_test.MmsReceiver: java.lang.NullPointerException: println needs a message
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3154)
        at android.app.ActivityThread.-wrap18(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1612)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6317)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
     Caused by: java.lang.NullPointerException: println needs a message
        at android.util.Log.println_native(Native Method)
        at android.util.Log.v(Log.java:122)
        at com.klinker.android.send_message.MmsReceivedReceiver.onReceive(MmsReceivedReceiver.java:93)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3143)
        at android.app.ActivityThread.-wrap18(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1612) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6317) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
```

The error appears to come from [this line in MmsReceivedReceiver](https://github.com/klinker41/android-smsmms/blob/master/library/src/main/java/com/klinker/android/send_message/MmsReceivedReceiver.java#L93).

**Comment by Gulshan31** [comment]
Hi any update on this?
