### ISSUE TITLE
com.android.mms.service_alt.exception.MmsNetworkException: Acquiring network timed out at Google Pixel Android 11

### ISSUE THREAD

**Issue by BareumSW** [klinker41/android-smsmms#188]
- There is no issue under Android 10
- Issue is with Android 11 / Google Pixel Phone
- No issue on Galaxy Android 11
- Issue Log
com.android.mms.service_alt.MmsNetworkManager [acquireNetwork] MmsNetworkManager: start new network request
[ConnectivityThread] com.android.mms.service_alt.MmsNetworkManager [onAvailable] **NetworkCallbackListener.onAvailable: network=505**
W/System.err: java.io.IOException: com.android.mms.service_alt.exception.MmsNetworkException: **Acquiring network timed out**
W/System.err:     at .Utils.ensureRouteToMmsNetworkMarshmallow(Utils.java:119)
W/System.err:     at .Utils.ensureRouteToMmsNetwork(Utils.java:96)
W/System.err:     at .Transaction.trySending(Transaction.java:1339)
W/System.err:     at .Transaction.access$500(Transaction.java:103)
W/System.err:     at .Transaction$6.run(Transaction.java:1215)
W/System.err:     at java.lang.Thread.run(Thread.java:923)
W/System.err: Caused by: com.android.mms.service_alt.exception.MmsNetworkException: Acquiring network timed out
W/System.err:     at com.android.mms.service_alt.MmsNetworkManager.acquireNetwork(MmsNetworkManager.java:151)
W/System.err:     at .Utils.ensureRouteToMmsNetworkMarshmallow(Utils.java:113)
W/System.err: 	... 5 more

**Comment by cdslily** [comment]
@BareumSW  

i have the same issue,do you resolve it?

thank you!
