### ISSUE TITLE
App crash in Android 12 

### ISSUE THREAD

**Issue by monikasavaliya** [klinker41/android-smsmms#190]
- **Crash Log**
java.lang.IllegalArgumentException: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:382)
	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:673)
	at android.app.PendingIntent.getBroadcast(PendingIntent.java:660)
	at com.klinker.android.send_message.Transaction.sendSmsMessage(Transaction.java:267)
	at com.klinker.android.send_message.Transaction.sendNewMessage(Transaction.java:158)
	at com.klinker.android.send_message.Transaction.sendNewMessage(Transaction.java:172)

**Comment by tibbi** [comment]
doesnt look like creating PRs makes sense, so you can try using my fork of the library with including `com.github.tibbi:android-smsmms:5413948b41`. It has only this 1 difference compared to the main project.

**Comment by masonljh** [comment]
> doesnt look like creating PRs makes sense, so you can try using my fork of the library with including `com.github.tibbi:android-smsmms:5413948b41`. It has only this 1 difference compared to the main project.

thank you for sharing your pr
I hope your pr is merged.
