### ISSUE TITLE
MMS send issue on Samsung Galaxy S3/S4 devices

### ISSUE THREAD

**Issue by celeronpm** [klinker41/android-smsmms#2]
In MmsMessageSender.java line 110 fails 

SqliteWrapper.insert(mContext, mContext.getContentResolver(), PendingMessages.CONTENT_URI, values);

This line throws an UnsupportedOperationException on the Galaxy S3/S4 devices due to the PendingMessages.CONTENT_URI. Apparently this does not exists on these devices.

As a consequence, the TransactionService never picks up the message to send since its status is outbox rather than pending and message just sits in outbox with spinning circle in default app indefinitely.

**Comment by KurdAppDev** [comment]
on Galaxy S4 mini

0-27 14:04:42.805 2839-3896/com.klinker.android.send_message.sample E/Transaction: exception thrown
                                                                                    java.lang.UnsupportedOperationException: MmsSmsProvider does not support deletes, inserts, or updates for this URI.
                                                                                        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:169)
                                                                                        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:137)
                                                                                        at android.content.ContentProviderProxy.insert(ContentProviderNative.java:420)
                                                                                        at android.content.ContentResolver.insert(ContentResolver.java:869)
                                                                                        at com.google.android.mms.util_alt.SqliteWrapper.insert(SqliteWrapper.java:112)
                                                                                        at com.android.mms.transaction.MmsMessageSender.sendMessage(MmsMessageSender.java:116)
                                                                                        at com.klinker.android.send_message.Transaction.sendMmsMessage(Transaction.java:371)
                                                                                        at com.klinker.android.send_message.Transaction.sendNewMessage(Transaction.java:140)
                                                                                        at com.klinker.android.messaging_sample.MainActivity$8.run(MainActivity.java:221)
                                                                                        at java.lang.Thread.run(Thread.java:856)

**Comment by ratchetasslife** [comment]
8282286959

**Comment by ratchetasslife** [comment]
Duplicate of # Joshuacorpening
