### ISSUE TITLE
com.android.mms.util.DownloadManager.getInstance Uninitialized

### ISSUE THREAD

**Issue by WMariusz** [klinker41/android-smsmms#25]
i recieve an error

11-28 13:42:18.540: E/AndroidRuntime(29782): FATAL EXCEPTION: main
11-28 13:42:18.540: E/AndroidRuntime(29782): Process: com.maxcom.launcher, PID: 29782
11-28 13:42:18.540: E/AndroidRuntime(29782): java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 (has extras) } in com.android.mms.transaction.TransactionService$ConnectivityBroadcastReceiver@4247d320
11-28 13:42:18.540: E/AndroidRuntime(29782):    at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:776)
11-28 13:42:18.540: E/AndroidRuntime(29782):    at android.os.Handler.handleCallback(Handler.java:733)
11-28 13:42:18.540: E/AndroidRuntime(29782):    at android.os.Handler.dispatchMessage(Handler.java:95)
11-28 13:42:18.540: E/AndroidRuntime(29782):    at android.os.Looper.loop(Looper.java:136)
11-28 13:42:18.540: E/AndroidRuntime(29782):    at android.app.ActivityThread.main(ActivityThread.java:5139)
11-28 13:42:18.540: E/AndroidRuntime(29782):    at java.lang.reflect.Method.invokeNative(Native Method)
11-28 13:42:18.540: E/AndroidRuntime(29782):    at java.lang.reflect.Method.invoke(Method.java:515)
11-28 13:42:18.540: E/AndroidRuntime(29782):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
11-28 13:42:18.540: E/AndroidRuntime(29782):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
11-28 13:42:18.540: E/AndroidRuntime(29782):    at dalvik.system.NativeStart.main(Native Method)
11-28 13:42:18.540: E/AndroidRuntime(29782): Caused by: java.lang.IllegalStateException: Uninitialized.
11-28 13:42:18.540: E/AndroidRuntime(29782):    at com.android.mms.util.DownloadManager.getInstance(DownloadManager.java:86)
11-28 13:42:18.540: E/AndroidRuntime(29782):    at com.android.mms.transaction.RetryScheduler.scheduleRetry(RetryScheduler.java:150)
11-28 13:42:18.540: E/AndroidRuntime(29782):    at com.android.mms.transaction.RetryScheduler.update(RetryScheduler.java:85)
11-28 13:42:18.540: E/AndroidRuntime(29782):    at com.android.mms.transaction.Observable.notifyObservers(Observable.java:72)
11-28 13:42:18.540: E/AndroidRuntime(29782):    at com.android.mms.transaction.TransactionService$ServiceHandler.markAllPendingTransactionsAsFailed(TransactionService.java:718)
11-28 13:42:18.540: E/AndroidRuntime(29782):    at com.android.mms.transaction.TransactionService$ConnectivityBroadcastReceiver.onReceive(TransactionService.java:892)
11-28 13:42:18.540: E/AndroidRuntime(29782):    at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:766)
11-28 13:42:18.540: E/AndroidRuntime(29782):    ... 9 more
11-28 13:43:33.630: E/Crashlytics(29782): Error occurred sending report com.crashlytics.android.Z@42740570

and i wonder is its wont be better to change 

```
public static DownloadManager getInstance() {
    if (sInstance == null) {
        throw new IllegalStateException("Uninitialized.");
    }
    return sInstance;
}
```

to 

```
public static DownloadManager getInstance(Context context) {
    if (sInstance == null) {
        sInstance = new DownloadManager(context);
    }
    return sInstance;
}
```

**Comment by adrien-aubel** [comment]
Got the same. Throwing `IllegalStateException` from there sounds (very) dangerous.
