### ISSUE TITLE
Failed to send MMS under some Android device

### ISSUE THREAD

**Issue by dingzhexue** [klinker41/android-smsmms#3]
How are you?

I tried to send MMS on 2 type of Android devices.

Succeed to send MMS under first Android device(Samsung Galaxy Note 3, Android 4.3, Possible to get phone number, SIM with China Mobile).

Failed to send MMS under secondary Android device(Nexus 5, Android 4.4, Impossible to get phone number, SIM with China Unicom).

Here are the log against the failed message sent to mms.

01-04 04:08:54.457: V/sending_mms_library(10438): error saving mms message
01-04 04:08:54.457: W/System.err(10438): com.google.android.mms.MmsException: unable to update content://mms/1388779734454/part/0
01-04 04:08:54.457: W/System.err(10438):    at com.google.android.mms.pdu_alt.PduPersister.persistData(PduPersister.java:798)
01-04 04:08:54.457: W/System.err(10438):    at com.google.android.mms.pdu_alt.PduPersister.persistPart(PduPersister.java:759)
01-04 04:08:54.457: W/System.err(10438):    at com.google.android.mms.pdu_alt.PduPersister.persist(PduPersister.java:1389)
01-04 04:08:54.457: W/System.err(10438):    at com.klinker.android.send_message.Transaction.getBytes(Transaction.java:423)
01-04 04:08:54.457: W/System.err(10438):    at com.klinker.android.send_message.Transaction.sendMmsMessage(Transaction.java:309)
01-04 04:08:54.467: W/System.err(10438):    at com.klinker.android.send_message.Transaction.sendNewMessage(Transaction.java:140

01-04 04:08:54.497: V/sending_mms_library(10438): still an error saving... :(
01-04 04:08:54.497: W/System.err(10438): java.io.FileNotFoundException: App op not allowed
01-04 04:08:54.497: W/System.err(10438):    at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:146)
01-04 04:08:54.497: W/System.err(10438):    at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:611)
01-04 04:08:54.497: W/System.err(10438):    at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:922)
01-04 04:08:54.497: W/System.err(10438):    at android.content.ContentResolver.openOutputStream(ContentResolver.java:669)
01-04 04:08:54.507: W/System.err(10438):    at android.content.ContentResolver.openOutputStream(ContentResolver.java:645)
01-04 04:08:54.507: W/System.err(10438):    at com.klinker.android.send_message.Transaction.createPartImage(Transaction.java:1055)
01-04 04:08:54.507: W/System.err(10438):    at com.klinker.android.send_message.Transaction.insert(Transaction.java:1020)
01-04 04:08:54.507: W/System.err(10438):    at com.klinker.android.send_message.Transaction.getBytes(Transaction.java:429)
01-04 04:08:54.507: W/System.err(10438):    at com.klinker.android.send_message.Transaction.sendMmsMessage(Transaction.java:309)
01-04 04:08:54.507: W/System.err(10438):    at com.klinker.android.send_message.Transaction.sendNewMessage(Transaction.java:140)

01-04 04:08:54.507: W/System.err(10438): java.lang.IllegalArgumentException: Null message URI.
01-04 04:08:54.517: W/System.err(10438):    at com.android.mms.transaction.MmsMessageSender.<init>(MmsMessageSender.java:63)
01-04 04:08:54.517: W/System.err(10438):    at com.klinker.android.send_message.Transaction.sendMmsMessage(Transaction.java:312)
01-04 04:08:54.517: W/System.err(10438):    at com.klinker.android.send_message.Transaction.sendNewMessage(Transaction.java:140)

I hope that you let me know the solution.

Thanks,
HaiLong

**Comment by complitech** [comment]
Hello, I am facing this same issue, Does anybody have resolved this ?

**Comment by pilootchoum** [comment]
Facing same issue on Sony XperiaE4 - Android 4.4.4

**Comment by necklinux** [comment]
Facing same issue on Lenovo S898t+ - Android 4.4.2

**Comment by necklinux** [comment]
Set this app to be default SMS App to solve my problem.
(How to set default SMS app: https://www.cnet.com/how-to/manage-default-sms-app-on-android-4-4-kitkat/)

**Comment by mcconkiee** [comment]
so sorry to bring this back to life, but i'm curious if there is  a way to send MMS in the background but NOT be the default app?

**Comment by klinker41** [comment]
Not possible due to framework limitations on Android 4.4 and higher.

**Comment by tozblue** [comment]
Without default SMS App setting, can send MMS?

**Comment by klinker24** [comment]
@tozblue the previous comment answers this question. It is not possible due to framework limitations on Android 4.4 and above.

**Comment by shn-dev** [comment]
Which framework limitations? Can you explain why this fork works when the default activity is not set? @klinker24  @klinker41 

https://github.com/DrBrad/android-smsmms
