### ISSUE TITLE
NPE getDataEnabled  & WRITE_APN_SETTINGS permission

### ISSUE THREAD

**Issue by xsorifc28** [klinker41/android-smsmms#43]
Here is the error I get when trying to send an MMS on Lollipop:

    exception thrown
    java.lang.NoSuchMethodException: getDataEnabled [int]
            at java.lang.Class.getMethod(Class.java:664)
            at java.lang.Class.getMethod(Class.java:643)
            at com.klinker.android.send_message.Utils.isDataEnabled(Utils.java:255)
            at com.android.mms.service_alt.MmsRequest.isMobileDataEnabled(MmsRequest.java:131)
            at com.android.mms.service_alt.MmsRequest.isDataNetworkAvailable(MmsRequest.java:135)
            at com.android.mms.service_alt.MmsRequest.execute(MmsRequest.java:170)
            at com.klinker.android.send_message.Transaction.sendMmsMessage(Transaction.java:434)
            at com.klinker.android.send_message.Transaction.sendNewMessage(Transaction.java:143)
          ...
            at android.app.Activity.dispatchActivityResult(Activity.java:6179)
            at android.app.ActivityThread.deliverResults(ActivityThread.java:3638)
            at android.app.ActivityThread.handleSendResult(ActivityThread.java:3685)
            at android.app.ActivityThread.access$1300(ActivityThread.java:149)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1375)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:211)
            at android.app.ActivityThread.main(ActivityThread.java:5335)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)

    E/MmsRequest﹕ MmsRequest: unexpected failure
    java.lang.SecurityException: No permission to write APN settings
            at android.os.Parcel.readException(Parcel.java:1547)
            at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:185)
            at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:137)
            at android.content.ContentProviderProxy.query(ContentProviderNative.java:420)
            at android.content.ContentResolver.query(ContentResolver.java:482)
            at android.content.ContentResolver.query(ContentResolver.java:426)
            at android.database.sqlite.SqliteWrapper.query(SqliteWrapper.java:59)
            at com.android.mms.service_alt.ApnSettings.load(ApnSettings.java:117)
            at com.android.mms.service_alt.MmsRequest.execute(MmsRequest.java:192)
            at com.klinker.android.send_message.Transaction.sendMmsMessage(Transaction.java:434)
            at com.klinker.android.send_message.Transaction.sendNewMessage(Transaction.java:143)
           ...
            at android.app.Activity.dispatchActivityResult(Activity.java:6179)
            at android.app.ActivityThread.deliverResults(ActivityThread.java:3638)
            at android.app.ActivityThread.handleSendResult(ActivityThread.java:3685)
            at android.app.ActivityThread.access$1300(ActivityThread.java:149)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1375)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:211)
            at android.app.ActivityThread.main(ActivityThread.java:5335)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)

..althoug I'm not trying to write APN settings?

**Comment by klinker41** [comment]
This error is normal on most devices and accounted for. It is not what is
failing the sending, you'll need to post more of the log, there should be
another error further down.

**Comment by xsorifc28** [comment]
I can't get it to log to an external file, and nothing else is showing up in logcat. 

Code for enabling logging? ..

    final File root = new File(Environment.getExternalStorageDirectory() + java.io.File.separator + "myapp" + java.io.File.separator);

    Settings.setDebugLogging(true, root.getPath());

**Comment by xsorifc28** [comment]
Futher Information:

The MMS's show up as sent under my default Messaing app (Sony XPERIA Z3+ default), but do not actually send (receiver does not get the message).

If I switch my messaging app to Hangouts, the MMS's sent do not show up. 

In my app, I am attempting to send an MMS via button click. Does my app need to be the default messaging app to send?

**Comment by klinker41** [comment]
Yes, you definitely need to be the default app to send mms.

**Comment by xsorifc28** [comment]
Ah, okay. Thanks!
