### ISSUE TITLE
Sending MMS on 7.1 pixel XL Carrier Project Fi not sending

### ISSUE THREAD

**Issue by SirSaunders** [klinker41/android-smsmms#61]
I had trouble with gradle compiling this  in my own project so I cloned the sample to test if it worked or not and I got the fallowing error sending the MMS picture and I downloaded  Sliding Messaging Pro to see if that would work - Group messaging and any other MMS would not work their either for the pixel. 

``12-11 20:44:14.054 17432-17752/com.klinker.android.send_message.sample E/Transaction: error using system sending method
                                                                                      com.google.android.mms.MmsException: unable to update content://mms/1481507054043/part/0
                                                                                          at com.google.android.mms.pdu_alt.PduPersister.persistData(PduPersister.java:835)
                                                                                          at com.google.android.mms.pdu_alt.PduPersister.persistPart(PduPersister.java:758)
                                                                                          at com.google.android.mms.pdu_alt.PduPersister.persist(PduPersister.java:1435)
                                                                                          at com.klinker.android.send_message.Transaction.sendMmsThroughSystem(Transaction.java:565)
                                                                                          at com.klinker.android.send_message.Transaction.sendMmsMessage(Transaction.java:415)
                                                                                          at com.klinker.android.send_message.Transaction.sendNewMessage(Transaction.java:140)
                                                                                          at com.klinker.android.messaging_sample.MainActivity$8.run(MainActivity.java:221)
                                                                                          at java.lang.Thread.run(Thread.java:761)

**Comment by klinker24** [comment]
I have a pixel on project Fi. The "System Controlled MMS" settings work great. But sliding messaging has never been updated to include the latest changes in this library, so I am pretty confident that it definitely won't work there.

**Comment by SirSaunders** [comment]
My apologies, the sample app refused to send the first time I tried it because I never set it as default but I got it to work now. I hope to incorporate this library in my current project and will try to contribute if and when I can.
 Thank you
