### ISSUE TITLE
MMS Received Receipt Throwing Error 

### ISSUE THREAD

**Issue by searchy2** [klinker41/android-smsmms#62]
@aTakayukiMorita

Latest Commit e8ac714968e232e9d666878f18a548a3eae3d704 with new MMSReceivedReceiver CommonAsyncTask throws error. Is the read receipt working correctly in your build? 

```
12-13 18:15:46.176 23749-27104/com.secretmessage E/Mms: Url: http://mms.msg.eng.t-mobile.com/mms/wapenc
                                                        HTTP error: Found
12-13 18:15:46.186 23749-27104/com.secretmessage E/MmsReceivedReceiver: error
                                                                        java.io.IOException: HTTP error: Found
                                                                            at com.android.mms.transaction.HttpUtils.handleHttpConnectionException(HttpUtils.java:294)
                                                                            at com.android.mms.transaction.HttpUtils.httpConnection(HttpUtils.java:280)
                                                                            at com.secretmessage.send.MmsReceivedReceiver$CommonAsyncTask.sendPdu(MmsReceivedReceiver.java:215)
                                                                            at com.secretmessage.send.MmsReceivedReceiver$CommonAsyncTask.sendPdu(MmsReceivedReceiver.java:180)
                                                                            at com.secretmessage.send.MmsReceivedReceiver$NotifyRespTask.doInBackground(MmsReceivedReceiver.java:244)
                                                                            at com.secretmessage.send.MmsReceivedReceiver$NotifyRespTask.doInBackground(MmsReceivedReceiver.java:225)
                                                                            at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                            at java.lang.Thread.run(Thread.java:818)
                                                                         Caused by: java.io.IOException: HTTP error: Found
                                                                            at com.android.mms.transaction.HttpUtils.httpConnection(HttpUtils.java:203)
                                                                            at com.secretmessage.send.MmsReceivedReceiver$CommonAsyncTask.sendPdu(MmsReceivedReceiver.java:215) 
                                                                            at com.secretmessage.send.MmsReceivedReceiver$CommonAsyncTask.sendPdu(MmsReceivedReceiver.java:180) 
                                                                            at com.secretmessage.send.MmsReceivedReceiver$NotifyRespTask.doInBackground(MmsReceivedReceiver.java:244) 
                                                                            at com.secretmessage.send.MmsReceivedReceiver$NotifyRespTask.doInBackground(MmsReceivedReceiver.java:225) 
                                                                            at android.os.AsyncTask$2.call(AsyncTask.java:295) 
                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                            at java.lang.Thread.run(Thread.java:818)
```

**Comment by aTakayukiMorita** [comment]
I tested it with the server which url is http://mms.ezweb.ne.jp/MMS. CommonAsyncTask throws no error. 
I think that the operation may differ depending on the setting. It is difficult for me to get the environment which can connect to http://mms.msg.eng.t-mobile.com/mms/wapenc.

**Comment by searchy2** [comment]
Closing due to inactivity.
