### ISSUE TITLE
on receiving MMS time out

### ISSUE THREAD

**Issue by KurdAppDev** [klinker41/android-smsmms#63]
12-20 18:31:51.500 1893-32482/? E/MmsService: [DownloadRequest@dc8a55a] MmsNetworkManager: timed out
12-20 18:31:51.511 1893-32482/? E/MmsService: [DownloadRequest@dc8a55a] MMS network acquiring failure
                                              com.android.mms.service.exception.MmsNetworkException: Acquiring network timed out
                                                  at com.android.mms.service.MmsNetworkManager.acquireNetwork(MmsNetworkManager.java:149)
                                                  at com.android.mms.service.MmsRequest.execute(MmsRequest.java:153)
                                                  at com.android.mms.service.MmsService$2.run(MmsService.java:427)
                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                  at java.lang.Thread.run(Thread.java:818)

**Comment by klinker24** [comment]
If you are getting a timeout here, it is probably an issue with the APNs. Are you able to send correctly through your APN settings?

**Comment by E3V3A** [comment]
Perhaps using [port 80](https://github.com/klinker41/android-smsmms/blob/master/library/src/main/java/com/android/mms/service_alt/ApnSettings.java#L169
) is the problem? Most APNs are using higher ports.

**Comment by SirSaunders** [comment]
It may be an issue on some Android 7.0 devices? Found this post for Textra talking about it. [](https://textra.uservoice.com/knowledgebase/articles/1147366-mms-timeouts-no-mobile-data-mms-send-failing)
