### ISSUE TITLE
Receiving MMS puts weird thread_id into content resolver?

### ISSUE THREAD

**Issue by NickM-27** [klinker41/android-smsmms#70]
First off thanks for the hard work on this library! It is really amazing!

So I am having a weird issue with receiving MMS. I have a class which extends PushReceiver and when it gets a WAP_DELIVER intent I call super.onReceive(context, intent) and then process the data to get the address of the message. 

Next I get the content resolver of Uri content://mms/ and try to get the most recent message from that (so that I can write it to my database and notify the user) only there is a very long thread_id which is given to the messages received by the library (the thread_id seems to link to an all MMS thread or something, maybe a download history thread). This thread id also doesn't allow me to get the pdu parts. Whenever I use a different SMS app and check the content resolver it has the thread_id of the conversation with the person and allows me to get the pdu parts for the message.

I am wondering: Is this a bug with the library getting a thread_id, is there a better way to get the actual thread_id / data so that I can get the message info, and is there an all together better way of getting the incoming mms information?

Thanks! :D

**Comment by klinker24** [comment]
Here is the MMS receiver from [Pulse SMS](). This is how I do it with our latest app. It does not extend `PushReceiver`, it extends the `MmsReceivedReceiver` from this library.

```java
/**
 * Receiver for notifying us when a new MMS has been received by the device. By default it will
 * persist the message to the internal database. We also need to add functionality for
 * persisting it to our own database and giving a notification that it has been received.
 */
public class MmsReceivedReceiver extends com.klinker.android.send_message.MmsReceivedReceiver {

    private Long conversationId = null;

    @Override
    public void onReceive(Context context, Intent intent) {
        super.onReceive(context, intent);

        String nullableOrBlankBodyText = insertMms(context);

        if (nullableOrBlankBodyText != null && !nullableOrBlankBodyText.isEmpty() && conversationId != null) {
            Intent mediaParser = new Intent(context, MediaParserService.class);
            mediaParser.putExtra(MediaParserService.EXTRA_CONVERSATION_ID, conversationId);
            mediaParser.putExtra(MediaParserService.EXTRA_BODY_TEXT, nullableOrBlankBodyText.trim());
            new Handler().postDelayed(() -> context.startService(mediaParser), 2000);
        }

        context.startService(new Intent(context, NotificationService.class));
    }

    private String insertMms(Context context) {
        Cursor lastMessage = SmsMmsUtils.getLastMmsMessage(context);

        String snippet = "";
        if (lastMessage != null && lastMessage.moveToFirst()) {
            Uri uri = Uri.parse("content://mms/" + lastMessage.getLong(0));
            final String from = SmsMmsUtils.getMmsFrom(uri, context);

            if (BlacklistUtils.isBlacklisted(context, from)) {
                return null;
            }

            final String to = SmsMmsUtils.getMmsTo(uri, context);
            final String phoneNumbers = getPhoneNumbers(from, to,
                    PhoneNumberUtils.getMyPhoneNumber(context), context);
            List<ContentValues> values = SmsMmsUtils.processMessage(lastMessage, -1L, context);

            DataSource source = DataSource.getInstance(context);
            source.open();

            for (ContentValues value : values) {
                Message message = new Message();
                message.type = value.getAsInteger(Message.COLUMN_TYPE);
                message.data = value.getAsString(Message.COLUMN_DATA).trim();
                message.timestamp = value.getAsLong(Message.COLUMN_TIMESTAMP);
                message.mimeType = value.getAsString(Message.COLUMN_MIME_TYPE);
                message.read = false;
                message.seen = false;
                message.from = ContactUtils.findContactNames(from, context);
                message.simPhoneNumber = DualSimUtils.get(context).getAvailableSims().isEmpty() ? null : to;

                if (message.mimeType.equals(MimeType.TEXT_PLAIN)) {
                    snippet = message.data;
                }

                if (phoneNumbers.split(", ").length == 1) {
                    message.from = null;
                }

                if (SmsReceivedReceiver.shouldSaveMessages(source, message)) {
                    conversationId = source.insertMessage(message, phoneNumbers, context);

                    if (MmsSettings.get(context).autoSaveMedia &&
                            !MimeType.TEXT_PLAIN.equals(message.mimeType)) {
                        new MediaSaver(context).saveMedia(message);
                    }
                }
            }

            source.close();

            if (conversationId != null) {
                ConversationListUpdatedReceiver.sendBroadcast(context, conversationId,
                        snippet, false);
                MessageListUpdatedReceiver.sendBroadcast(context, conversationId);
            }
        }

        try {
            lastMessage.close();
        } catch (Exception e) { }

        return snippet;
    }

    @VisibleForTesting
    protected String getPhoneNumbers(String from, String to, String myNumber, Context context) {
        String[] toNumbers = to.split(", ");
        StringBuilder builder = new StringBuilder();
        String myName = getMyName(context);
        
        for (String number : toNumbers) {
            String cleanNumber = PhoneNumberUtils.clearFormatting(number);
            String myCleanNumber = PhoneNumberUtils.clearFormatting(myNumber);
            String contactName = ContactUtils.findContactNames(number, context);
            
            if (!cleanNumber.contains(myCleanNumber) && !myCleanNumber.contains(cleanNumber) && !contactName.equals(myName)) {
                builder.append(number);
                builder.append(", ");
            }
        }

        builder.append(from);
        return builder.toString();
    }

    @VisibleForTesting
    protected String getMyName(Context context) {
        return Account.get(context).myName;
    }

    @VisibleForTesting
    protected String getContactName(Context context, String number) {
        return ContactUtils.findContactNames(number, context);
    }

}
```

**Comment by klinker41** [comment]
Note that implementation works when using the `Settings#setUseSystemSending`.

**Comment by NickM-27** [comment]
@klinker24 Can I see the SmsMmsUtils.getlastMmsMesssage method? Because it seems that I am still getting an invalid thread id when using receiving the mms. Just to be clear about my setup:

I have a class which extends PushReceiver and in its onReceive method it calls super.onReceive and then launches the receiver which extends MmsReceivedReceiver. Whenever I tried calling super.onReceive in the MmsReceived class, I get a null point exception. Am I supposed to launch that receiver from a specific intent or something? Thanks!

**Comment by klinker24** [comment]
The library launches the receiver for you, when you have it defined. I don't extend `PushReceiver` anywhere in the code I posted.

**Comment by NickM-27** [comment]
@klinker24 Okay so I have this working now. I have the standard receiver which extends PushReceiver (as the README shows) and then the MmsReceivedReceiver which has the intent filter as seen in the manifest of the sample. The issue now is that whenever I call super.onReceive from the mmsreceiver I get this crash:

```
java.lang.NoSuchMethodError: No direct method <init>(Lcom/google/android/mms/pdu_alt/GenericPdu;IJ)V in class Lcom/google/android/mms/util_alt/PduCacheEntry; or its super classes (declaration of 'com.google.android.mms.util_alt.PduCacheEntry' appears in /data/data/com.nick.mowen.texpert/files/instant-run/dex/slice-slice_8-classes.dex)
                                                                            at com.google.android.mms.pdu_alt.PduPersister.load(PduPersister.java:671)
                                                                            at com.klinker.android.send_message.MmsReceivedReceiver.getNotificationInd(MmsReceivedReceiver.java:134)
                                                                            at com.klinker.android.send_message.MmsReceivedReceiver.getNotificationTask(MmsReceivedReceiver.java:308)
                                                                            at com.klinker.android.send_message.MmsReceivedReceiver.onReceive(MmsReceivedReceiver.java:85)
                                                                            at com.nick.mowen.texpert.receiver.MmsBroadcastReceiver.access$super(MmsBroadcastReceiver.java)
                                                                            at com.nick.mowen.texpert.receiver.MmsBroadcastReceiver$override.onReceive(MmsBroadcastReceiver.java:34)
                                                                            at com.nick.mowen.texpert.receiver.MmsBroadcastReceiver$override.access$dispatch(MmsBroadcastReceiver.java)
                                                                            at com.nick.mowen.texpert.receiver.MmsBroadcastReceiver.onReceive(MmsBroadcastReceiver.java:0)
                                                                            at android.app.ActivityThread.handleReceiver(ActivityThread.java:3040)
                                                                            at android.app.ActivityThread.-wrap18(ActivityThread.java)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1561)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by NickM-27** [comment]
@klinker24 @klinker41 Any chance y'all know what this crash is caused by? Maybe some residual files or something that is messing it up and not having it happen on Pulse? Sorry for the hassle, I just really want to get this working for my app as it will be the last thing I need. Thanks!

**Comment by klinker24** [comment]
Looks like it is missing an internal class, so I imagine that you are trying to use the system sending method and don't have a device new enough to support it? I don't know though

**Comment by NickM-27** [comment]
@klinker24 I am using a Nexus 6P on 7.2 beta on the network Project Fi. Is project Fi maybe causing it to have some weird issues?

**Comment by klinker24** [comment]
Yes, like Jake said above

**Comment by NickM-27** [comment]
@klinker24 Okay, so that could be the part that is messing with it. I was confused because it seemed like Settings were only needed / looked at when sending a message. After looking through the sample it seems that maybe using Settings.get(this) will allow me to set systemSending for the whole library. Is this correct or do I need to set it a different way to receive using system? Thanks so much for your help

**Comment by NickM-27** [comment]
@klinker41 So when I send MMS I set useSystemSending as true. This is the only time that I could think to set that. Is there a different point / different object I need to set it as true so that it will be used for receiving? Thanks again

**Comment by klinker41** [comment]
No. Have you simply tried the sample app included? It implements everything you need to implement already.

**Comment by NickM-27** [comment]
@klinker24 @klinker41 Yeah I'm sorry, I definitely should have tried that sooner. After running the sample I realized the issue was that I still had my own version of the google pdu files. I am not sure how but it seems to have gotten in the way. After removing those files, everything works as expected. Thanks so much for your help!

**Comment by akramul-hasan-m4** [comment]
Please add a separate simple sample about -  **MMS send and receive** with <kbd>MMS</kbd> apn settings. it will helps for begainers.
#### OR
Make a complete Wiki for this library.

*Thank you for your amazing library*
