### ISSUE TITLE
Crash (DeliveredReceiver) after sending SMS with delivery report set.

### ISSUE THREAD

**Issue by rmukund** [klinker41/android-smsmms#71]
Hi, thanks a ton for the great library! 

I have an crash to report when turning on delivery receipt for SMS.

I am Using version 3.5.0, here is the relevant snippet -

        Settings sendSettings = new Settings();

        Transaction transaction = new Transaction(mContext, sendSettings);

        if (needReceipt) sendSettings.setDeliveryReports(true);

The SMS is sent successfully, but resulting in a crash in DeliveredReceiver (where the status is updated in SMS table).
_com.klinker.android.send_message.DeliveredReceiver.onReceive(DeliveredReceiver.java:60)_

Here is the complete trace, I will be glad to send any more information you may need.

        java.lang.RuntimeException: Unable to start receiver com.klinker.android.send_message.DeliveredReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
            at android.app.ActivityThread.handleReceiver(ActivityThread.java:2753)
            at android.app.ActivityThread.access$1700(ActivityThread.java:162)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1489)
            at android.os.Handler.dispatchMessage(Handler.java:106)
            at android.os.Looper.loop(Looper.java:189)
            at android.app.ActivityThread.main(ActivityThread.java:5532)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)
         Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
            at android.os.Parcel.readException(Parcel.java:1546)
            at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:185)
            at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:137)
            at android.content.ContentProviderProxy.update(ContentProviderNative.java:567)
            at android.content.ContentResolver.update(ContentResolver.java:1377)
            at com.klinker.android.send_message.DeliveredReceiver.onReceive(DeliveredReceiver.java:60)
            at android.app.ActivityThread.handleReceiver(ActivityThread.java:2746)
            at android.app.ActivityThread.access$1700(ActivityThread.java:162) 
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1489) 
            at android.os.Handler.dispatchMessage(Handler.java:106) 
            at android.os.Looper.loop(Looper.java:189) 
            at android.app.ActivityThread.main(ActivityThread.java:5532) 
            at java.lang.reflect.Method.invoke(Native Method) 
            at java.lang.reflect.Method.invoke(Method.java:372) 
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950) 
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)

**Comment by rmukund** [comment]
I ran the latest version of QKSMS app with delivery receipt turned on. That crashes too, I just wanted to check if the issue is just with how I am using the library.

**Comment by klinker41** [comment]
It is probably an issue with the library, I've never used delivery reports as none of my carriers have supported them. Feel free to fix and open a pull request.
