### ISSUE TITLE
catch in var29

### ISSUE THREAD

**Issue by ElttonAraujo** [klinker41/android-smsmms#94]
Somebody can help me ? I try sending a mms, but all time happens catch var 29 in below method.
private static void sendMmsThroughSystem(Context context, String subject, List<MMSPart> parts, String[] addresses, Intent explicitSentMmsReceiver) {
        try {
            String e = "send." + String.valueOf(Math.abs((new Random()).nextLong())) + ".dat";
            File mSendFile = new File(context.getCacheDir(), e);
            Log.d(".messaging_sample", String.valueOf(context.getCacheDir()));
            SendReq sendReq = buildPdu(context, addresses, subject, parts);
            PduPersister persister = PduPersister.getPduPersister(context);
            Uri messageUri = persister.persist(sendReq, Uri.parse("content://mms/outbox"), true, settings.getGroup(), (HashMap)null);
            Log.d(".messaging_sample", mSendFile.getPath());
            Intent intent;
            if(explicitSentMmsReceiver == null) {
                intent = new Intent("com.klinker.android.messaging.MMS_SENT");
                BroadcastUtils.addClassName(context, intent, "com.klinker.android.messaging.MMS_SENT");
            } else {
                intent = explicitSentMmsReceiver;
            }

            intent.putExtra("content_uri", messageUri.toString());
            Log.d(".messaging_sample", messageUri.toString());
            intent.putExtra("file_path", mSendFile.getPath());
            PendingIntent pendingIntent = PendingIntent.getBroadcast(context, 0, intent, 268435456);
            Uri writerUri = (new Builder()).authority(context.getPackageName() + ".MmsFileProvider").path(e).scheme("content").build();
            FileOutputStream writer = null;
            Uri contentUri = null;

            try {
                writer = new FileOutputStream(mSendFile);
                writer.write((new PduComposer(context, sendReq)).make());
                contentUri = writerUri;
            } catch (IOException var27) {
                Log.e("Transaction", "Error writing send file", var27);
            } finally {
                if(writer != null) {
                    try {
                        writer.close();
                    } catch (IOException var25) {
                        ;
                    }
                }

            }

            Bundle configOverrides = new Bundle();
            configOverrides.putBoolean("enableGroupMms", settings.getGroup());
            String httpParams = MmsConfig.getHttpParams();
            if(!TextUtils.isEmpty(httpParams)) {
                configOverrides.putString("httpParams", httpParams);
            }

            configOverrides.putInt("maxMessageSize", MmsConfig.getMaxMessageSize());
            if(contentUri != null) {
                SmsManagerFactory.createSmsManager(settings).sendMultimediaMessage(context, contentUri, (String)null, configOverrides, pendingIntent);
            } else {
                Log.e("Transaction", "Error writing sending Mms");

                try {
                    pendingIntent.send(5);
                } catch (CanceledException var26) {
                    Log.e("Transaction", "Mms pending intent cancelled?", var26);
                }
            }
        } catch (Exception var29) {
            Log.e("Transaction", "error using system sending method", var29);
        }

**Comment by klinker24** [comment]
Can you post the stack trace?

**Comment by ElttonAraujo** [comment]
unfortunately i can't send. However, the mistake on strack is system_process E/ActivityManager: Sending non-protected broadcast. My manifest and broadcasts are virtually the same used in API sample. As also, i'm using system permission in my manifest.

**Comment by klinker24** [comment]
If you could post the full stack trace of the exception, that would be the easiest way for me to take a look

**Comment by ElttonAraujo** [comment]
Unfortunately this is a stealth project. Therefore, can't send you the full stack trace. This is a max that i can send.

at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:18168)
                                                                   at com.android.server.am.ActivityManagerService.broadcastIntentInPackage(ActivityManagerService.java:18785)
                                                                   at com.android.server.am.PendingIntentRecord.sendInner(PendingIntentRecord.java:319)
                                                                   at com.android.server.am.PendingIntentRecord.sendWithResult(PendingIntentRecord.java:216)
                                                                   at com.android.server.am.ActivityManagerService.sendIntentSender(ActivityManagerService.java:7442)
                                                                   at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:3032)
                                                                   at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2904)
                                                                   at android.os.Binder.execTransact(Binder.java:565)

**Comment by klinker24** [comment]
Sorry but that doesn't really tell me much. I think if you want help, we will need the full trace. At least what part of the library code it is getting caught at.

**Comment by ElttonAraujo** [comment]
I identified the problem. However, the solution is yet nebulous. Its possible use this API with system permission in manifest (android:sharedUserId="android.uid.system") ?. If yes, how ?

**Comment by klinker41** [comment]
That is set in your application, it shouldn't have anything to do with the library.

**Comment by ElttonAraujo** [comment]
Hi, I corrected the error, however I wanna a question. When i send a mms, the sender is occult therefore, this is lack of configuration or doesn't the API work anyway ?

**Comment by klinker41** [comment]
Sorry, I'm not sure I understand your question.

**Comment by ElttonAraujo** [comment]
When I send a sms it arrives at the recipient with all the desired information. But when I send an MMS the same arrives without the sender's data. How do I solve this?

**Comment by klinker41** [comment]
I have no idea. Sender data comes from your carrier, not this library.
